services:
  currency-swap-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173' # Vite dev server default port
    volumes:
      - .:/app
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    command: npm run dev
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
